version: '3.1'
services:
  stats-server:
    build: ./stats
    image: explorewithme-stats
    container_name: stats
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: db_stats
    ports:
      - "6511:5412"
    environment:
      - POSTGRES_DB=explorewithme_stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./server
    image: explorewithme-server
    container_name: server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: db_server
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme_server
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test