version: '3.1'
services:
  stats-server:
    build: ./stats
    image: explorewithme-stats
    container_name: stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6511:5412"
    environment:
      - POSTGRES_DB=explorewithme_stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./server
    image: explorewithme-server
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - "stats-server"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme_server
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test